<?php
return array (
  'autogenerated-1-c4ca4238a0b923820dcc509a6f75849b' => 
  array (
    'base' => 'http://localhost/dpblog/helloworld',
    'frontendBase' => '',
    'headless' => 1,
    'languages' => 
    array (
      0 => 
      array (
        'title' => 'English',
        'enabled' => true,
        'languageId' => 0,
        'base' => '/',
        'locale' => 'en_US.UTF-8',
        'navigationTitle' => 'English',
        'flag' => 'us',
      ),
    ),
    'rootPageId' => 1,
    'websiteTitle' => '',
  ),
  'autogenerated-2-c81e728d9d4c2f636f067f89cc14862c' => 
  array (
    'base' => 'http://localhost/dpblog/images',
    'frontendBase' => '',
    'headless' => 1,
    'languages' => 
    array (
      0 => 
      array (
        'title' => 'English',
        'enabled' => true,
        'languageId' => 0,
        'base' => '/',
        'locale' => 'en_US.UTF-8',
        'navigationTitle' => 'English',
        'flag' => 'us',
      ),
    ),
    'rootPageId' => 2,
    'websiteTitle' => '',
  ),
  'autogenerated-7-8f14e45fceea167a5a36dedd4bea2543' => 
  array (
    'base' => 'http://localhost/dpblog/blogData',
    'frontendBase' => '',
    'headless' => 1,
    'languages' => 
    array (
      0 => 
      array (
        'title' => 'English',
        'enabled' => true,
        'languageId' => 0,
        'base' => '/',
        'locale' => 'en_US.UTF-8',
        'navigationTitle' => 'English',
        'flag' => 'us',
      ),
    ),
    'rootPageId' => 7,
    'websiteTitle' => '',
  ),
  'autogenerated-8-c9f0f895fb98ab9159f51fd0297e236d' => 
  array (
    'base' => 'http://localhost/dpblog/about',
    'frontendBase' => '',
    'headless' => 1,
    'languages' => 
    array (
      0 => 
      array (
        'title' => 'English',
        'enabled' => true,
        'languageId' => 0,
        'base' => '/',
        'locale' => 'en_US.UTF-8',
        'navigationTitle' => 'English',
        'flag' => 'us',
      ),
    ),
    'rootPageId' => 8,
    'websiteTitle' => '',
  ),
);
#