<?php

// autoload_classmap.php @generated by TYPO3

$typo3InstallDir = \TYPO3\CMS\Core\Core\Environment::getPublicPath() . '/';

return array(
    'FriendsOfTYPO3\\Headless\\' => array($typo3InstallDir . 'typo3conf/ext/headless/Classes'),
);
