base: 'http://localhost/dpblog/blogData'
frontendBase: ''
headless: 1
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /
    locale: en_US.UTF-8
    navigationTitle: English
    flag: us
rootPageId: 7
websiteTitle: ''
